POST http://localhost:1338/xAPI/statements HTTP/1.1
Content-Type: application/json
X-Experience-API-Version: 1.0.3

{
  "actor": {
    "mbox": "mailto:dummy@example.org"
  },
  "verb": {
    "id": "http://example.org/dummy_verb"
  },
  "object": {
    "id": "http://example.org/dummy_activity",
    "definition": {
      "name": {
        "en-GB": "hello",
        "fr": "bonjour"
      }
    }
  }
}
